name: Build iOS IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build App
        run: |
          xcodebuild \
          -scheme Example-iOS \
          -sdk iphoneos \
          -configuration Release \
          -derivedDataPath output \
          CODE_SIGNING_ALLOWED=NO

      - name: Create Payload
        run: |
          mkdir Payload
          cp -R output/Build/Products/Release-iphoneos/Example-iOS.app Payload/

      - name: Create IPA
        run: |
          zip -r Example-iOS.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Example-iOS-IPA
          path: Example-iOS.ipa
